-- Snowflake production-hardening migration.
-- Run the warehouse section as SYSADMIN and the role/grant section as SECURITYADMIN.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DBT_PROD_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

GRANT USAGE, OPERATE ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE DBT_PROD_WH TO ROLE DBT_ROLE;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ANALYTICS_READER_ROLE;
GRANT ROLE ANALYTICS_READER_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE PROD TO ROLE ANALYTICS_READER_ROLE;

-- dbt creates target-derived schemas such as ANALYTICS_MARTS during the first build.
-- Run these grants after that first build if the schema does not exist yet.
GRANT USAGE ON SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
