-- Snowflake production-hardening migration.
-- Run the role creation section as USERADMIN, object creation as SYSADMIN,
-- and grants as SECURITYADMIN (or use an equivalent administrative role).

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS ANALYTICS_READER_ROLE;
GRANT ROLE ANALYTICS_READER_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DBT_PROD_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE SCHEMA IF NOT EXISTS DEV.DBT_DEV_STAGING;
CREATE SCHEMA IF NOT EXISTS DEV.DBT_DEV_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DEV.DBT_DEV_MARTS;

CREATE SCHEMA IF NOT EXISTS PROD.ANALYTICS_STAGING;
CREATE SCHEMA IF NOT EXISTS PROD.ANALYTICS_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PROD.ANALYTICS_MARTS;

USE ROLE SECURITYADMIN;

GRANT USAGE, OPERATE ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE DBT_PROD_WH TO ROLE DBT_ROLE;

GRANT USAGE ON DATABASE DEV TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEV.DBT_DEV_STAGING TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEV.DBT_DEV_INTERMEDIATE TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEV.DBT_DEV_MARTS TO ROLE DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DEV.DBT_DEV_STAGING TO ROLE DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DEV.DBT_DEV_INTERMEDIATE TO ROLE DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DEV.DBT_DEV_MARTS TO ROLE DEV_ROLE;

GRANT USAGE ON DATABASE PROD TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA PROD.ANALYTICS_STAGING TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA PROD.ANALYTICS_INTERMEDIATE TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA PROD.ANALYTICS_MARTS TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PROD.ANALYTICS_STAGING TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PROD.ANALYTICS_INTERMEDIATE TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PROD.ANALYTICS_MARTS TO ROLE DBT_ROLE;

GRANT USAGE ON DATABASE PROD TO ROLE ANALYTICS_READER_ROLE;
GRANT USAGE ON SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROD.ANALYTICS_MARTS TO ROLE ANALYTICS_READER_ROLE;
