-- Adds persistent ingestion metadata to the existing RAW Olist tables.
-- Run as a role that owns or can alter RAW.OLIST tables.
-- Existing rows are backfilled once. Future ingestion should populate _LOADED_AT at load time.

ALTER TABLE RAW.OLIST.CUSTOMER ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.ORDERS ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.ORDER_ITEMS ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.ORDER_PAYMENTS ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.ORDER_REVIEWS ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.PRODUCTS ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.SELLERS ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.GEOLOCATION ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW.OLIST.PRODUCT_CATEGORY_NAME_TRANSLATION ADD COLUMN IF NOT EXISTS _LOADED_AT TIMESTAMP_NTZ;

UPDATE RAW.OLIST.CUSTOMER
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.ORDERS
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.ORDER_ITEMS
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.ORDER_PAYMENTS
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.ORDER_REVIEWS
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.PRODUCTS
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.SELLERS
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.GEOLOCATION
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

UPDATE RAW.OLIST.PRODUCT_CATEGORY_NAME_TRANSLATION
SET _LOADED_AT = CURRENT_TIMESTAMP()
WHERE _LOADED_AT IS NULL;

-- Validation: every table should return zero NULL ingestion timestamps.
SELECT 'CUSTOMER' AS TABLE_NAME, COUNT_IF(_LOADED_AT IS NULL) AS NULL_LOADED_AT FROM RAW.OLIST.CUSTOMER
UNION ALL
SELECT 'ORDERS', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.ORDER_ITEMS
UNION ALL
SELECT 'ORDER_PAYMENTS', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.ORDER_PAYMENTS
UNION ALL
SELECT 'ORDER_REVIEWS', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.ORDER_REVIEWS
UNION ALL
SELECT 'PRODUCTS', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.PRODUCTS
UNION ALL
SELECT 'SELLERS', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.SELLERS
UNION ALL
SELECT 'GEOLOCATION', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.GEOLOCATION
UNION ALL
SELECT 'PRODUCT_CATEGORY_NAME_TRANSLATION', COUNT_IF(_LOADED_AT IS NULL) FROM RAW.OLIST.PRODUCT_CATEGORY_NAME_TRANSLATION;
